### ISSUE TITLE
[BUG] Names don't adhere to plugin naming convention

### ISSUE THREAD

**Issue by mnkugler** [opensearch-project/asynchronous-search#209]
**What is the bug?**
As per https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#opensearch-plugins, the folder name needs to adhere to the naming convention

**What is the expected behavior?**
[Folder needs to be created and Include full plugin name in kebab case, e.g., plugins/opensearch-asynchronous-search](https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#folders)

**Do you have any additional context?**
Referred to here:
https://github.com/opensearch-project/opensearch-plugins/issues/174

**Comment by mnkugler** [comment]
Hi @Arpit-Bandejiya . Noticed you are assign to this issue. Can you provide a status update on resolving this?

**Comment by Arpit-Bandejiya** [comment]
Hi, the build file is in the root directory and this is a core opensearch plugin and I see that other core plugins are following the same convention: https://github.com/opensearch-project/cross-cluster-replication, https://github.com/opensearch-project/security . @mnkugler can you please explain the ask and the prerequisite for the change for a plugin?

**Comment by Arpit-Bandejiya** [comment]
Also we are following the naming convention in the build.gradle here: https://github.com/opensearch-project/asynchronous-search/blob/main/build.gradle#LL148C22-L148C34

**Comment by Arpit-Bandejiya** [comment]
Closing the issue since I don't think there is anything to be changed. Pleae re-open if there are any concerns thanks!
