### ISSUE TITLE
Add auto github release workflow

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/asynchronous-search#234]
### Is your feature request related to a problem?
As part of OpenSearch releases, `opensearch-build` pushes a tag for the release commit.
But publishing a github release based on the tag is manual.

### What solution would you like?
We've added this workflow[1] in OpenSearch which publishes github releases automatically when a tag is pushed.

Add this workflow to all repos releasing software in the project.
See example: https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/auto-release.yml
Example Release: https://github.com/opensearch-project/OpenSearch/releases/tag/2.5.0

[1] https://github.com/opensearch-project/opensearch-plugins/blob/main/WORKFLOWS.md#auto-github-releases

**Comment by Arpit-Bandejiya** [comment]
@saratvemulapalli  @gaiksaya we have added the auto-release workflow. How can we verify that it is working as expected?

**Comment by gaiksaya** [comment]
Added a comment in the above PR but you can test it in your fork by replacing the [Github token](https://github.com/opensearch-project/asynchronous-search/pull/330/files#diff-5a93af5afcdcd2bdc566f58652f8af7fec28b2d02acb9bec8ee97e9334362731R28) by your own personal token stored in secrets and ofcourse comment out token retrieval [here](https://github.com/opensearch-project/asynchronous-search/pull/330/files#diff-5a93af5afcdcd2bdc566f58652f8af7fec28b2d02acb9bec8ee97e9334362731R15-R21). And then push a tag to your fork. 
Thanks!

**Comment by Arpit-Bandejiya** [comment]
Have taken note of the comment. Closing the issue
