### ISSUE TITLE
[FEATURE] Onboard distribution level BWC bundle test

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/asynchronous-search#517]
Currently asynchronous repo has BWC test on plugin level and only tested within the repo. We have a framework for BWC distribution level test available and you could utilize it and enable distribution level BWC test.

With this framework, you would be able to spin up the test cluster with the latest distribution bundle that engineering effectiveness team generated that installs all the other components. This test will be more comprehensive as it will test the exact product we ship to the customers. 

Onboarding this distribution level BWC test can also enable engineering effectiveness team to run BWC tests every time ee team generates a new bundle distribution across each of the plugin through CI

More onboarding info can be found here:
https://github.com/opensearch-project/opensearch-plugins/blob/main/TESTING.md#bwc-tests-on-distribution-bundle-level

**What solution would you like?**
Similar to what we did to the anomaly-detection plugin. https://github.com/opensearch-project/anomaly-detection/pull/766
Enable bundle level BWC test based on the BWC test you already have.

**Comment by anasalkouz** [comment]
@bbarani Could you elaborate more? why this will be a blocker for 2.15?

**Comment by bbarani** [comment]
@anasalkouz We are planning to add BWC tests as mandatory exit criteria starting 2.15.0 release as we are seeing more number of BWC test failures during releases.

**Comment by finnegancarroll** [comment]
I'll take this!
