### ISSUE TITLE
[BUG] MAINTAINERS and CODEOWNERS are out of sync

### ISSUE THREAD

**Issue by dblock** [opensearch-project/asynchronous-search#531]
**What is the bug?**

```
https://github.com/opensearch-project/asynchronous-search: 5
 missing_in_codeowners: ["RS146BIJAY"]
 missing_in_maintainers: ["dhruv16dhr"]
```

**What is the expected behavior?**

MAINTAINERS and CODEOWNERS should be in sync.

**Comment by RS146BIJAY** [comment]
Thanks for pointing this out @dblock. I believe this happened because of recent change to update maintainer list. Will fix this.

**Comment by anasalkouz** [comment]
It should be fixed. https://github.com/opensearch-project/asynchronous-search/pull/551
