### ISSUE TITLE
[BUG] Async-Search in OS 3.0

### ISSUE THREAD

**Issue by Tokesh** [opensearch-project/asynchronous-search#607]
**What is the bug?**
Hello everyone! 
I [wrote specs for async-search ](https://github.com/opensearch-project/opensearch-api-specification/pull/525#top) in [OpenSearch-api-specification](https://github.com/opensearch-project/opensearch-api-specification) repo
We test all our PRs in different versions of OpenSearch. 
So, as i understand, `async-search` is already available in OS 3.0, but i cant find a tag that i can use.
I tried using the [latest tag](https://hub.docker.com/layers/opensearchstaging/opensearch/3.0.0/images/sha256-ec7b9f5edabec15412e2e4d58268d0e40d900c57bb59fa62a09e41b991d0f596?context=explore), but it doesnt work.
Do I understand correctly that async search should be [in version 3.0?](https://github.com/opensearch-project/asynchronous-search/issues/502)

**How can one reproduce the bug?**
use `async-search` APIs with latest tag of OS 3.0
mostly i got `[INFO] <= 400 (application/json) | "no handler found for uri [/_plugins/_asynchronous_search] and method [POST]"`

**What is the expected behavior?**
It should work in 3.0 the same as in 2.x, or its bug

**What is your host/environment?**
[Docker CI configs](https://github.com/opensearch-project/opensearch-api-specification/actions/runs/10531306492/job/29183179121)
 - OS: Ubuntu
 - Version 22.04
 - Plugins

**Do you have any additional context?**
I'm newbie at this repo. I’m always happy to make new connections and meet friendly people here. You can ask me any questions, I will try to answer as quickly as possible and my colleagues from our repository.

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/andrross), [3](https://github.com/sandervandegeijn), [4](https://github.com/AmiStrn), [5](https://github.com/udabhas)]
