### ISSUE TITLE
Remove jcenter repository

### ISSUE THREAD

**Issue by mch2** [opensearch-project/asynchronous-search#89]
## Description
JCenter has been turned off and should be removed as a referenced repository.

Please Remove any direct dependency on jcenter() within a repositories block in gradle files.

Related: https://github.com/opensearch-project/opensearch-build/issues/1456

**Comment by peternied** [comment]
@opensearch-project/asynchronous-search can this be triaged and prioritized?

**Comment by eirsep** [comment]
Sure @peternied 

We will pick this up.

**Comment by peternied** [comment]
Looks like this has been resolved, closing
