### ISSUE TITLE
Change the "Master" nomenclature

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/asynchronous-search#99]
**Is your feature request related to a problem? Please describe.**
[OpenSearch](https://github.com/opensearch-project/OpenSearch) repository is going to replace the terminology "master"with "cluster manager".
issue: https://github.com/opensearch-project/OpenSearch/issues/472#issuecomment-960298995, with the plan for its terminology replacement.

Although the existing usages with "master" will be supported in OpenSearch version 2.x to keep the backwards compatibility, please prepare for the nomenclature change in advance, and replace all the usages with "master" terminology in the code base.
All the OpenSearch REST APIs and settings that contain "master" terminology will be deprecated in 2.0, and alternative usages will be added.

**Describe the solution you'd like**
Replace the terminology "master" with "cluster manager".

When being compatible with OpenSearch 2.0:
- Replace "master" in code comment and internal variable / method name.
- Replace OpenSearh REST API that contains "master" with the provided inclusive REST API:
replace ["master_timeout"](https://github.com/opensearch-project/asynchronous-search/blob/1.3.1.0/src/test/java/org/opensearch/search/asynchronous/utils/RestTestUtils.java#L261) with "cluster_manager_timeout"

When being compatible with OpenSearch 3.0:
- Replace "master" in the reference to OpenSearch Java API
(new APIs are available in version 2.2)
  - [ ] DiscoveryNodes.builder().masterNodeId() -> `clusterManagerNodeId()`
  - [ ] DiscoveryNodeRole.MASTER_ROLE -> `CLUSTER_MANAGER_ROLE`
  - [ ] event.localNodeMaster() -> `localNodeClusterManager()`

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by dhruv16dhr** [comment]
Closing this issue as the changes are merged

**Comment by dblock** [comment]
I see methods like `.localNodeMaster()` in the code still. Is this waiting on something in OpenSearch?

**Comment by tlfeng** [comment]
@dblock That's correct. `.localNodeMaster()` depends on the change in the OpenSearch class:
https://github.com/opensearch-project/asynchronous-search/blob/1c28a085fe7e77695c7756a8feb997914708be68/src/main/java/org/opensearch/search/asynchronous/management/AsynchronousSearchManagementService.java#L20
The rename is tracked in issue https://github.com/opensearch-project/OpenSearch/issues/1684. 
It will be ready before OpenSearch 3.0 and I will complete in advance and keep update.
If the issue is used for pending items for 2.0 release, then the issue is resolved.

**Comment by dblock** [comment]
I've removed the 2.0 label in favor of 2.1 for the remaining work.

**Comment by eirsep** [comment]
changed label to v3.0.0 as there are no 2.1 related master deprecation items for the plugin

**Comment by anasalkouz** [comment]
Java APIs completed and released on 2.2.
@dhruv16dhr  Could you please complete the remaining part from your end? let's target 2.3 to remove all usages.

**Comment by anasalkouz** [comment]
@dhruv16dhr anything remaining? can you close the issue?
